## Analysis of dirty dataset

In [24]:


dirty_customers = pd.read_csv(
    "../data/raw/customers_dirty.csv"
)

In [25]:
dirty_customers.shape

(502, 7)

In [26]:
dirty_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    502 non-null    str
 1   customer_name  502 non-null    str
 2   city           501 non-null    str
 3   state          502 non-null    str
 4   customer_type  501 non-null    str
 5   credit_limit   502 non-null    int64
 6   created_at     502 non-null    str
dtypes: int64(1), str(6)
memory usage: 27.6 KB

In [27]:
dirty_customers.isnull().sum()

customer_id      0
customer_name    0
city             1
state            0
customer_type    1
credit_limit     0
created_at       0
dtype: int64

In [28]:
dirty_customers.duplicated().sum()

np.int64(2)

In [29]:
dirty_customers.dtypes

customer_id        str
customer_name      str
city               str
state              str
customer_type      str
credit_limit     int64
created_at         str
dtype: object

In [30]:
dirty_customers["credit_limit"].describe()

count       502.000000
mean     169870.517928
std      155126.415410
min      -50000.000000
25%       50000.000000
50%      100000.000000
75%      250000.000000
max      500000.000000
Name: credit_limit, dtype: float64

In [31]:
dirty_customers[
    dirty_customers["credit_limit"] <= 0
]

,customer_id,customer_name,city,state,customer_type,credit_limit,created_at
50,C00051,Mohit Traders,Ghaziabad,Uttar Pradesh,Distributor,-50000,2024-05-27
51,C00052,Rahul Enterprises,Hapur,Uttar Pradesh,Retailer,0,2022-06-10

In [32]:

pd.to_datetime(
    dirty_customers["created_at"],
    errors="coerce"
).isna().sum()

np.int64(1)

In [33]:
dirty_customers[
    dirty_customers["customer_name"] !=
    dirty_customers["customer_name"].str.strip()
]

,customer_id,customer_name,city,state,customer_type,credit_limit,created_at
40,C00041,Amit Traders,Hapur,Uttar Pradesh,Wholesaler,75000,2023-10-22

In [34]:
dirty_customers[
    dirty_customers["customer_name"] !=
    dirty_customers["customer_name"].str.title()
]

,customer_id,customer_name,city,state,customer_type,credit_limit,created_at
41,C00042,ARJUN STORE,Noida,Uttar Pradesh,Retailer,75000,2026-03-15

: